### ISSUE TITLE
Modification needed to use ha-unipi-neuron with UniPi1.1 hardware

### ISSUE THREAD

**Issue by HACSFox** [marko2276/ha-unipi-neuron#1]
Hi marko,
thank you for your effort creating this integration.
Trying to use it with UniPi 1.1 modules, I've discovered, that ports name or device circuit name scheme differs for UniPi V1.1 from your UniPi-Neuron implementation. 

The port number scheme differs for UniPi 1.1 ("/relay/1") from Neuron ("/relay/1_01").

 Thus, I've modified your code a little bit. 

The only flaw was the built in configuration validation, done by the regex check for the port value (in lights.py, line 36: `vol.Required(CONF_PORT): cv.matches_regex(r"^[1-3]_[0-1][0-9]")`,

I managed to add an regex alteration, thus both variants could be passed to Evok ,but only one will work, of course ("1" for UniPi or "1_01" for Neuron). Communication fails, if used within the wrong hardware

`vol.Required(CONF_PORT): cv.matches_regex(r"^[1-3]_[0-1][0-9]|[1-8]"),
`
One might add some `if else` code depending on the sofar unused Type parameter ("L203", "M203", "S203" ) and add "UniPi" to this type list.
But I'm not used to program with python, thus I'm happy with this little hack.

**Comment by marko2276** [comment]
This was merged in a while back (so closing the issue)
