### ISSUE TITLE
unique_id properties aren't unique at all, while using several devices with identical port scheme

### ISSUE THREAD

**Issue by HACSFox** [marko2276/ha-unipi-neuron#4]
@marko2276 
Hi Marko,
I found an issue with unique_ids.
Unfortunately, the current code does not work properly having more than one Unipi-devices with the same configuration(s).

In this case, the "unique_ids" will be identical for e.g. lights or switches on Unipi unit 1 and Unipi unit 2!
Thus, Homeassistant isn't able to determine the targets anymore and will disable them.

I managed to get around this issue by extending the unique_id property definition(s) like this:

```
@property
    def unique_id(self):
        """Return the unique ID of this light entity."""
        return f"{self._device}_{self._port}_at_{self._unipi_hub._name}"

```
Explanation:
"self._device" will be e.g. "relay" , it is not a representation of a unique hardware
"self._port" might be altered within EVOK.conf on devices with the feature (this is not possible on Unipi V1.1 units).
"self._unipi_hub._name" for instant will do the trick,

**Comment by marko2276** [comment]
Hi HACSFox

The unique_id field was actually added by @k3rn3l3rr0r a few month ago, so I must admit that I have not used it myself yet.
In any case, I would like to ask you, if you can open a formal pull request with your change and then let's see if we have any review comments.

Regards
Marko

**Comment by k3rn3l3rr0r** [comment]
Sorry for that, I just made a quick fix for my use case with a single Unipi... It's true that with multiple devices it will not be unique anymore.

**Comment by marko2276** [comment]
The changes to address the issue were merged in a while back.
