### ISSUE TITLE
deprecated supported features values which will be removed in HA Core 2025.1.

### ISSUE THREAD

**Issue by PlazzmiK** [marko2276/ha-unipi-neuron#7]
`WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.unipi_neuron.light.UnipiLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please report it to the author of the 'unipi_neuron' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`

**Comment by marko2276** [comment]
Thanks @PlazzmiK for the info. I will look into this and provide and update/fix.

**Comment by marko2276** [comment]
Latest commit should address this now.
