### ISSUE TITLE
doesn't work on Core 2024.5

### ISSUE THREAD

**Issue by anline380** [marko2276/ha-unipi-neuron#8]
Hi Marko,
thank you first for the great integration, which has worked wonderfully so far. Unfortunately, it is no longer compatible with Core 2024.5. The lights no longer indicate the correct state, and the binary sensors have completely gone. I had to revert to 2024.4.4 so that the house is not completely dead:( 
Thanks in advance,
Manuel

**Comment by Geunsjl** [comment]
I have the same issue, inputs not detected in HA 2024.5 and light status no longer correct (but it does switch them on or off).

Log:

Logger: homeassistant.util.logging
Bron: util/logging.py:98
Eerst voorgekomen: 14:53:29 (745 gebeurtenissen)
Laatst gelogd: 16:57:06

Exception in _update_callback when dispatching 'unipi_neuron_L207_PLC_input_UART_3_3_02': () Traceback (most recent call last): File "/config/custom_components/unipi_neuron/binary_sensor.py", line 105, in _update_callback self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state self.hass.verify_event_loop_thread("async_write_ha_state") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'unipi_neuron' calls async_write_ha_state from a thread at custom_components/unipi_neuron/binary_sensor.py, line 105: self.async_write_ha_state(). Please report it to the author of the 'unipi_neuron' custom integration.
Exception in _update_callback when dispatching 'unipi_neuron_L207_PLC_input_UART_3_3_04': () Traceback (most recent call last): File "/config/custom_components/unipi_neuron/binary_sensor.py", line 105, in _update_callback self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state self.hass.verify_event_loop_thread("async_write_ha_state") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'unipi_neuron' calls async_write_ha_state from a thread at custom_components/unipi_neuron/binary_sensor.py, line 105: self.async_write_ha_state(). Please report it to the author of the 'unipi_neuron' custom integration.
Exception in _update_callback when dispatching 'unipi_neuron_L207_PLC_input_UART_2_2_12': () Traceback (most recent call last): File "/config/custom_components/unipi_neuron/binary_sensor.py", line 105, in _update_callback self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state self.hass.verify_event_loop_thread("async_write_ha_state") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'unipi_neuron' calls async_write_ha_state from a thread at custom_components/unipi_neuron/binary_sensor.py, line 105: self.async_write_ha_state(). Please report it to the author of the 'unipi_neuron' custom integration.
Exception in _update_callback when dispatching 'unipi_neuron_L207_PLC_relay_3_13': () Traceback (most recent call last): File "/config/custom_components/unipi_neuron/light.py", line 169, in _update_callback self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state self.hass.verify_event_loop_thread("async_write_ha_state") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'unipi_neuron' calls async_write_ha_state from a thread at custom_components/unipi_neuron/light.py, line 169: self.async_write_ha_state(). Please report it to the author of the 'unipi_neuron' custom integration.
Exception in _update_callback when dispatching 'unipi_neuron_L207_PLC_relay_3_11': () Traceback (most recent call last): File "/config/custom_components/unipi_neuron/light.py", line 169, in _update_callback self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state self.hass.verify_event_loop_thread("async_write_ha_state") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'unipi_neuron' calls async_write_ha_state from a thread at custom_components/unipi_neuron/light.py, line 169: self.async_write_ha_state(). Please report it to the author of the 'unipi_neuron' custom integration.

**Comment by Geunsjl** [comment]
Okay I did some searching and replacing async_write_ha_state() with schedule_update_ha_state() seems to do the trick.
Changed it in binary_sensor.py and light.py. Cover.py already had this for some reason?

**Comment by anline380** [comment]
I'll try to use your suggested solution in the next few days (half of my house didn't work after the update). A big thank you for the quick support, Manuel

**Comment by Geunsjl** [comment]
I am not sure how active the main contributor still is in this github code, but in my logs I see a few alerts a out code that will be deprivated in 2025, so be aware of that...

**Comment by marko2276** [comment]
Hi @anline380  and @Geunsjl. 
Sorry for late response. I am still on an older version of HA and do not update it regularly. I will look into this issue as soon as I find some time (Hopefully by the end of this week).

Regards
Marko

**Comment by marko2276** [comment]
Hi @anline380 and @Geunsjl.
I have made required updates and fixes to work with latest HA core. Please check it out.

**Comment by Geunsjl** [comment]
@marko2276 I just tested it and it lights/inputs seem to work. I use 2x the XS11 so it complained about the config not being valid (see image). I changed the regex back to the previous one to allow UART in the config.

![UNIPI](https://github.com/marko2276/ha-unipi-neuron/assets/3920178/beb536ed-1ba7-4174-bb0a-dcd32d29ef0e)

**Comment by marko2276** [comment]
Hi @Geunsjl 

Which regex did you change to previous one (as in my commit, I do not recall of changing any regex?. Was it perhaps changed in some older commits?
Anyhow, can you please open a formal pull request, so that we can include your fixes?

Regards,
Marko
